apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tema-day-2
    service: webserver
  name: tema-day-2
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /tema-day-2
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "300m"
        memory: "64Mi"
  - image: busybox
    name: busybox
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "256Mi"
status: {}
