apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas   # Corrigido de "app: giropops-senha"
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 32500
      targetPort: 5000 # Corrigido de 32767 para 5000
      name: tcp-app
  type: NodePort      

