apiVersion: v1
kind: Service
metadata:
  name: giropops-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None #esse eh o item mais importante
  selector:
    app: nginx


