# o k8s será a certificadora que irá assinar nossos certificados
# não deixar o simbolo de % no final request
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6K1Y2UHNzMzRrVVY1M1ZYb3lTNjN3cHpZSFlMa2tpVlVLSENjMlkvClRDNjlDZURyZkVMejBGdUJYdmNacHNUdWdWc0puNXZmS0NTV2E2WEJRNHV3Q0VkU29ENk1LMUVkYWhnekF0OFcKeGpwZndyWFhuTTVVR3FIbGxEUXM5R290SEJLNXVGVWFmbTBxN0JvV0d1ekIzQ29IVlRTZHQxRFE3aXpZV3E1VQp1MFRwb2xsNU1jT2U0RWFhTTV1aHh4VzFvVUxVVDVVK0RUMXBtTDY1NGhmNVp0emlPaDUzN0doTVAyQU9WSEZtCmhacjJ2VlpTRVB4ajhiSFRGK1A1VG0yRVBqRlNpQW5zUUVhNDZ4K0kyNFZqZmlTV251WjhSZXBZNndub0FUZWEKQnEzd0pDalcxQWwySkxTV0x2enFYbXhrMnlqa2tWTDQ3L29VN0M4d0FBSmxiUUlEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUhabldxZnJodjlTWEVWYlJWQmVsQlJTRWVDQ0VFUWxxTlQ1TSt3UTBDaEc3S0JWCkk5TVNvR1hKMmF3TG81cWZPT1RJb1RrSm9Da1lhajNIWUJid21naWRrUGdRUHUzZjI5QkR5VEducGtuSVNuN2UKNWpjYWc3UkowdUlucGpIVUMzdk4yOW93aDZFYzl5U0ZUVW0rVTI2eVNJb2xBY0VtQ1lYT2VFc0x4S1lLOVdsZApCb2RRNEh5OVluc2wrNFpmQUdxN1Y2OVFYOUJUV1dhcDNKQW5mdXRxSEtUcml0NGhxQlZ4bFllUEE1VEEyMko1CmFsSjY5eDdTYWRSZHdaaG5paXZrNzh5TjRDZEpHN1NHeXhZektqZnkzV21TeWlKL1F1cVBaM3RGOThzMFp4bk0KVWdJQjcwZkJMY2F3bHZVM2srQlYzKzl4ZFBlODllZmRQajM4bngwPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K 
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000 #isso dá um ano
  usages:
  - client auth
