apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-service-account
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-leitor
roleRef:
  kind: Role
  name: service-account-role
  apiGroup: rbac.authorization.k8s.io
