apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    fruta: banana
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 10
  revisionHistoryLimit: 10
  selector: # eh atraves do selector que o K8s saberá quais pods gerenciar
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate # a outra opcao eh Recreate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.14.0
        name: nginx-opa
        resources:
          limits:
            cpu: 900m
            memory: 256Mi
          requests:
            cpu: 400m
            memory: 64Mi
