apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
spec:
  containers:
  - name: meu-container
    image: diogofiaminghi/conversao-temperatura:v1 #exemplo de imagem privada
  imagePullSecrets:
  - name: dockerhub-test 
